#!/bin/bash

mkdir /tmp/git
git clone ${GITADDR} /tmp/git
rsync -av --exclude=.git /tmp/git/ /var/www/html/
cd /tmp/git

/usr/local/bin/run-nginx &

while :; do
  git pull
  rsync -av --exclude=.git /tmp/git/ /var/www/html/
  sleep 300
done
