#!/bin/bash

mkdir /tmp/git
git clone ${GITADDR} /tmp/git
rsync -av --exclude=.git /tmp/git/ /usr/share/nginx/html/
cd /tmp/git

nginx -g "daemon off;" &

while :; do
  git pull
  rsync -av --exclude=.git /tmp/git/ /usr/share/nginx/html/
  sleep 300
done
